/**
 *
 *  DrogonTest.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "DrogonTest.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres;

const std::string DrogonTest::Cols::_id = "id";
const std::string DrogonTest::Cols::_message = "message";
const std::string DrogonTest::Cols::_msg_date = "msg_date";
const std::string DrogonTest::Cols::_errors = "errors";
const std::string DrogonTest::primaryKeyName = "id";
const bool DrogonTest::hasPrimaryKey = true;
const std::string DrogonTest::tableName = "drogon_test";

const std::vector<typename DrogonTest::MetaData> DrogonTest::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"message","std::string","character varying",255,0,0,1},
{"msg_date","::trantor::Date","date",0,0,0,0},
{"errors","std::string","character varying",255,0,0,0}
};
const std::string &DrogonTest::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
DrogonTest::DrogonTest(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["message"].isNull())
        {
            message_=std::make_shared<std::string>(r["message"].as<std::string>());
        }
        if(!r["msg_date"].isNull())
        {
            auto daysStr = r["msg_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            msgDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["errors"].isNull())
        {
            errors_=std::make_shared<std::string>(r["errors"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            message_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            msgDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            errors_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

DrogonTest::DrogonTest(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            message_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            msgDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            errors_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

DrogonTest::DrogonTest(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("message"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["message"].isNull())
        {
            message_=std::make_shared<std::string>(pJson["message"].asString());
        }
    }
    if(pJson.isMember("msg_date"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["msg_date"].isNull())
        {
            auto daysStr = pJson["msg_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            msgDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("errors"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["errors"].isNull())
        {
            errors_=std::make_shared<std::string>(pJson["errors"].asString());
        }
    }
}

void DrogonTest::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            message_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            msgDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            errors_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void DrogonTest::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("message"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["message"].isNull())
        {
            message_=std::make_shared<std::string>(pJson["message"].asString());
        }
    }
    if(pJson.isMember("msg_date"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["msg_date"].isNull())
        {
            auto daysStr = pJson["msg_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            msgDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("errors"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["errors"].isNull())
        {
            errors_=std::make_shared<std::string>(pJson["errors"].asString());
        }
    }
}

const int64_t &DrogonTest::getValueOfId() const noexcept
{
    const static int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &DrogonTest::getId() const noexcept
{
    return id_;
}
void DrogonTest::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename DrogonTest::PrimaryKeyType & DrogonTest::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &DrogonTest::getValueOfMessage() const noexcept
{
    const static std::string defaultValue = std::string();
    if(message_)
        return *message_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DrogonTest::getMessage() const noexcept
{
    return message_;
}
void DrogonTest::setMessage(const std::string &pMessage) noexcept
{
    message_ = std::make_shared<std::string>(pMessage);
    dirtyFlag_[1] = true;
}
void DrogonTest::setMessage(std::string &&pMessage) noexcept
{
    message_ = std::make_shared<std::string>(std::move(pMessage));
    dirtyFlag_[1] = true;
}

const ::trantor::Date &DrogonTest::getValueOfMsgDate() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(msgDate_)
        return *msgDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &DrogonTest::getMsgDate() const noexcept
{
    return msgDate_;
}
void DrogonTest::setMsgDate(const ::trantor::Date &pMsgDate) noexcept
{
    msgDate_ = std::make_shared<::trantor::Date>(pMsgDate.roundDay());
    dirtyFlag_[2] = true;
}
void DrogonTest::setMsgDateToNull() noexcept
{
    msgDate_.reset();
    dirtyFlag_[2] = true;
}

const std::string &DrogonTest::getValueOfErrors() const noexcept
{
    const static std::string defaultValue = std::string();
    if(errors_)
        return *errors_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DrogonTest::getErrors() const noexcept
{
    return errors_;
}
void DrogonTest::setErrors(const std::string &pErrors) noexcept
{
    errors_ = std::make_shared<std::string>(pErrors);
    dirtyFlag_[3] = true;
}
void DrogonTest::setErrors(std::string &&pErrors) noexcept
{
    errors_ = std::make_shared<std::string>(std::move(pErrors));
    dirtyFlag_[3] = true;
}
void DrogonTest::setErrorsToNull() noexcept
{
    errors_.reset();
    dirtyFlag_[3] = true;
}

void DrogonTest::updateId(const uint64_t id)
{
}

const std::vector<std::string> &DrogonTest::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "message",
        "msg_date",
        "errors"
    };
    return inCols;
}

void DrogonTest::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMessage())
        {
            binder << getValueOfMessage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMsgDate())
        {
            binder << getValueOfMsgDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getErrors())
        {
            binder << getValueOfErrors();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> DrogonTest::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void DrogonTest::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMessage())
        {
            binder << getValueOfMessage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMsgDate())
        {
            binder << getValueOfMsgDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getErrors())
        {
            binder << getValueOfErrors();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value DrogonTest::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMessage())
    {
        ret["message"]=getValueOfMessage();
    }
    else
    {
        ret["message"]=Json::Value();
    }
    if(getMsgDate())
    {
        ret["msg_date"]=getMsgDate()->toDbStringLocal();
    }
    else
    {
        ret["msg_date"]=Json::Value();
    }
    if(getErrors())
    {
        ret["errors"]=getValueOfErrors();
    }
    else
    {
        ret["errors"]=Json::Value();
    }
    return ret;
}

Json::Value DrogonTest::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMessage())
            {
                ret[pMasqueradingVector[1]]=getValueOfMessage();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMsgDate())
            {
                ret[pMasqueradingVector[2]]=getMsgDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getErrors())
            {
                ret[pMasqueradingVector[3]]=getValueOfErrors();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMessage())
    {
        ret["message"]=getValueOfMessage();
    }
    else
    {
        ret["message"]=Json::Value();
    }
    if(getMsgDate())
    {
        ret["msg_date"]=getMsgDate()->toDbStringLocal();
    }
    else
    {
        ret["msg_date"]=Json::Value();
    }
    if(getErrors())
    {
        ret["errors"]=getValueOfErrors();
    }
    else
    {
        ret["errors"]=Json::Value();
    }
    return ret;
}

bool DrogonTest::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("message"))
    {
        if(!validJsonOfField(1, "message", pJson["message"], err, true))
            return false;
    }
    else
    {
        err="The message column cannot be null";
        return false;
    }
    if(pJson.isMember("msg_date"))
    {
        if(!validJsonOfField(2, "msg_date", pJson["msg_date"], err, true))
            return false;
    }
    if(pJson.isMember("errors"))
    {
        if(!validJsonOfField(3, "errors", pJson["errors"], err, true))
            return false;
    }
    return true;
}
bool DrogonTest::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool DrogonTest::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("message"))
    {
        if(!validJsonOfField(1, "message", pJson["message"], err, false))
            return false;
    }
    if(pJson.isMember("msg_date"))
    {
        if(!validJsonOfField(2, "msg_date", pJson["msg_date"], err, false))
            return false;
    }
    if(pJson.isMember("errors"))
    {
        if(!validJsonOfField(3, "errors", pJson["errors"], err, false))
            return false;
    }
    return true;
}
bool DrogonTest::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool DrogonTest::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
